<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration 
{
    public function up(): void
    {
        Schema::dropIfExists('sme_datas');
        Schema::create('sme_datas', function (Blueprint $table) {
            $table->id();
            $table->string('data_id');
            $table->string('network');
            $table->string('plan_type');
            $table->string('amount');
            $table->string('size');
            $table->string('validity');
            $table->enum('status', ['enabled', 'disabled'])->default('enabled');
            $table->timestamps();
        });

        $data = [
            ['data_id' => '182', 'network' => '9MOBILE', 'plan_type' => 'GIFTING', 'amount' => '425.0', 'size' => '500.0 MB', 'validity' => '30 days{Gifting}'],
            ['data_id' => '183', 'network' => '9MOBILE', 'plan_type' => 'GIFTING', 'amount' => '850.0', 'size' => '1.5 GB', 'validity' => '30 days{Gifting}'],
            ['data_id' => '184', 'network' => '9MOBILE', 'plan_type' => 'GIFTING', 'amount' => '1020.0', 'size' => '2.0 GB', 'validity' => '30 days{Gifting}'],
            ['data_id' => '185', 'network' => '9MOBILE', 'plan_type' => 'GIFTING', 'amount' => '1275.0', 'size' => '3.0 GB', 'validity' => '30 days{Gifting}'],
            ['data_id' => '186', 'network' => '9MOBILE', 'plan_type' => 'GIFTING', 'amount' => '1700.0', 'size' => '4.5 GB', 'validity' => '30 days{Gifting}'],
            ['data_id' => '187', 'network' => '9MOBILE', 'plan_type' => 'GIFTING', 'amount' => '3400.0', 'size' => '11.0 GB', 'validity' => '30 days{Gifting}'],
            ['data_id' => '188', 'network' => '9MOBILE', 'plan_type' => 'GIFTING', 'amount' => '4200.0', 'size' => '15.0 GB', 'validity' => '30 days{Gifting}'],
            ['data_id' => '189', 'network' => '9MOBILE', 'plan_type' => 'GIFTING', 'amount' => '8500.0', 'size' => '40.0 GB', 'validity' => '30 days{Gifting}'],
            ['data_id' => '248', 'network' => '9MOBILE', 'plan_type' => 'SME', 'amount' => '220.0', 'size' => '1.0 GB', 'validity' => '1 month'],
            ['data_id' => '249', 'network' => '9MOBILE', 'plan_type' => 'SME', 'amount' => '330.0', 'size' => '1.5 GB', 'validity' => '1 month'],
            ['data_id' => '250', 'network' => '9MOBILE', 'plan_type' => 'SME', 'amount' => '720.0', 'size' => '2.0 GB', 'validity' => '1 month'],
            ['data_id' => '251', 'network' => '9MOBILE', 'plan_type' => 'SME', 'amount' => '660.0', 'size' => '3.0 GB', 'validity' => '1 month'],
            ['data_id' => '252', 'network' => '9MOBILE', 'plan_type' => 'SME', 'amount' => '880.0', 'size' => '4.0 GB', 'validity' => '1 month'],
            ['data_id' => '253', 'network' => '9MOBILE', 'plan_type' => 'SME', 'amount' => '1100.0', 'size' => '5.0 GB', 'validity' => '1 month'],
            ['data_id' => '262', 'network' => '9MOBILE', 'plan_type' => 'GIFTING', 'amount' => '12750.0', 'size' => '75.0 GB', 'validity' => '1 month'],
            ['data_id' => '269', 'network' => '9MOBILE', 'plan_type' => 'GIFTING', 'amount' => '46.0', 'size' => '25.0 MB', 'validity' => '1day'],
            ['data_id' => '270', 'network' => '9MOBILE', 'plan_type' => 'GIFTING', 'amount' => '175.0', 'size' => '650.0 MB', 'validity' => '1 day'],
            ['data_id' => '272', 'network' => '9MOBILE', 'plan_type' => 'GIFTING', 'amount' => '425.0', 'size' => '2000.0 MB', 'validity' => '3(2gb)days'],
            ['data_id' => '273', 'network' => '9MOBILE', 'plan_type' => 'GIFTING', 'amount' => '1275.0', 'size' => '7.0 GB', 'validity' => '7days(weekly)'],
            ['data_id' => '292', 'network' => '9MOBILE', 'plan_type' => 'SME', 'amount' => '2200.0', 'size' => '10.0 GB', 'validity' => '30days'],
            ['data_id' => '296', 'network' => '9MOBILE', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '480.0', 'size' => '1.0 GB', 'validity' => '30 days'],
            ['data_id' => '297', 'network' => '9MOBILE', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '960.0', 'size' => '2.0 GB', 'validity' => '30 days'],
            ['data_id' => '298', 'network' => '9MOBILE', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '720.0', 'size' => '1.5 GB', 'validity' => '30 days'],
            ['data_id' => '299', 'network' => '9MOBILE', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '1440.0', 'size' => '3.0 GB', 'validity' => '30 days'],
            ['data_id' => '300', 'network' => '9MOBILE', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '2400.0', 'size' => '5.0 GB', 'validity' => '30 days'],
            ['data_id' => '301', 'network' => '9MOBILE', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '4800.0', 'size' => '10.0 GB', 'validity' => '30 days'],
            ['data_id' => '302', 'network' => '9MOBILE', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '240.0', 'size' => '500.0 MB', 'validity' => '30 days'],
            ['data_id' => '303', 'network' => '9MOBILE', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '1920.0', 'size' => '4.0 GB', 'validity' => '30 days'],
            ['data_id' => '304', 'network' => '9MOBILE', 'plan_type' => 'SME', 'amount' => '980.0', 'size' => '4.5 GB', 'validity' => '30 days'],
            ['data_id' => '305', 'network' => '9MOBILE', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '25.0', 'size' => '25.0 MB', 'validity' => '30 days'],
            ['data_id' => '427', 'network' => 'AIRTEL', 'plan_type' => 'GIFTING', 'amount' => '2920.0', 'size' => '10.0 GB', 'validity' => '30DAYS VALIDITY'],
            ['data_id' => '428', 'network' => 'AIRTEL', 'plan_type' => 'SME', 'amount' => '2920.0', 'size' => '10.0 GB', 'validity' => '30DAYS VALIDITY'],
            ['data_id' => '436', 'network' => 'AIRTEL', 'plan_type' => 'GIFTING', 'amount' => '55.0', 'size' => '150.0 MB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '437', 'network' => 'AIRTEL', 'plan_type' => 'SME', 'amount' => '55.0', 'size' => '150.0 MB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '483', 'network' => 'AIRTEL', 'plan_type' => 'GIFTING', 'amount' => '290.0', 'size' => '1.0 GB', 'validity' => '3DAYS VALIDITY(social bundle)'],
            ['data_id' => '484', 'network' => 'AIRTEL', 'plan_type' => 'SME', 'amount' => '290.0', 'size' => '1.0 GB', 'validity' => '3DAYS VALIDITY(social bundle)'],
            ['data_id' => '485', 'network' => 'AIRTEL', 'plan_type' => 'GIFTING', 'amount' => '49800.0', 'size' => '13.0 GB', 'validity' => 'MIFI 30DAYS VALIDITY'],
            ['data_id' => '486', 'network' => 'AIRTEL', 'plan_type' => 'SME', 'amount' => '49800.0', 'size' => '13.0 GB', 'validity' => 'MIFI 30DAYS VALIDITY'],
            ['data_id' => '487', 'network' => 'AIRTEL', 'plan_type' => 'GIFTING', 'amount' => '99500.0', 'size' => '35.0 GB', 'validity' => '(MIFI) 30DAYS'],
            ['data_id' => '488', 'network' => 'AIRTEL', 'plan_type' => 'SME', 'amount' => '99500.0', 'size' => '35.0 GB', 'validity' => '(MIFI) 30DAYS'],
            ['data_id' => '489', 'network' => 'AIRTEL', 'plan_type' => 'GIFTING', 'amount' => '1490000.0', 'size' => '60.0 GB', 'validity' => '(MIFI) 30DAYS'],
            ['data_id' => '490', 'network' => 'AIRTEL', 'plan_type' => 'SME', 'amount' => '14900.0', 'size' => '60.0 GB', 'validity' => '(MIFI) 30DAYS'],
            ['data_id' => '515', 'network' => 'AIRTEL', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '490.0', 'size' => '500.0 MB', 'validity' => '7 days'],
            ['data_id' => '516', 'network' => 'AIRTEL', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '784.0', 'size' => '1.0 GB', 'validity' => '7 days'],
            ['data_id' => '517', 'network' => 'AIRTEL', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '1425.0', 'size' => '2.0 GB', 'validity' => '30 days'],
            ['data_id' => '518', 'network' => 'AIRTEL', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '1950.0', 'size' => '3.0 GB', 'validity' => '30 days'],
            ['data_id' => '519', 'network' => 'AIRTEL', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '2450.0', 'size' => '4.0 GB', 'validity' => '30 days'],
            ['data_id' => '520', 'network' => 'AIRTEL', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '2950.0', 'size' => '8.0 GB', 'validity' => '30 days'],
            ['data_id' => '521', 'network' => 'AIRTEL', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '3910.0', 'size' => '10.0 GB', 'validity' => '30 days'],
            ['data_id' => '522', 'network' => 'AIRTEL', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '4900.0', 'size' => '13.0 GB', 'validity' => '30 days'],
            ['data_id' => '523', 'network' => 'AIRTEL', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '5870.0', 'size' => '18.0 GB', 'validity' => '30 days'],
            ['data_id' => '524', 'network' => 'AIRTEL', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '7820.0', 'size' => '25.0 GB', 'validity' => '30 days'],
            ['data_id' => '525', 'network' => 'AIRTEL', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '75.0', 'size' => '75.0 MB', 'validity' => '1 Daily'],
            ['data_id' => '526', 'network' => 'AIRTEL', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '100.0', 'size' => '100.0 MB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '527', 'network' => 'AIRTEL', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '200.0', 'size' => '200.0 MB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '528', 'network' => 'AIRTEL', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '298.0', 'size' => '300.0 MB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '529', 'network' => 'AIRTEL', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '97500.0', 'size' => '35.0 GB', 'validity' => '30 days'],
            ['data_id' => '530', 'network' => 'AIRTEL', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '14600.0', 'size' => '60.0 GB', 'validity' => '30 days'],
            ['data_id' => '535', 'network' => 'AIRTEL', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '19500.0', 'size' => '100.0 GB', 'validity' => '30 days'],
            ['data_id' => '552', 'network' => 'AIRTEL', 'plan_type' => 'GIFTING', 'amount' => '735.0', 'size' => '3.0 GB', 'validity' => '1DAYS VALIDITY'],
            ['data_id' => '553', 'network' => 'AIRTEL', 'plan_type' => 'SME', 'amount' => '735.0', 'size' => '3.0 GB', 'validity' => '2 DAYS VALIDITY'],
            ['data_id' => '556', 'network' => 'AIRTEL', 'plan_type' => 'GIFTING', 'amount' => '55.0', 'size' => '150.0 MB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '557', 'network' => 'AIRTEL', 'plan_type' => 'SME', 'amount' => '55.0', 'size' => '150.0 MB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '558', 'network' => 'AIRTEL', 'plan_type' => 'GIFTING', 'amount' => '196.0', 'size' => '600.0 MB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '559', 'network' => 'AIRTEL', 'plan_type' => 'SME', 'amount' => '196.0', 'size' => '600.0 MB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '560', 'network' => 'AIRTEL', 'plan_type' => 'GIFTING', 'amount' => '98.0', 'size' => '300.0 MB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '561', 'network' => 'AIRTEL', 'plan_type' => 'SME', 'amount' => '98.0', 'size' => '300.0 MB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '592', 'network' => 'AIRTEL', 'plan_type' => 'GIFTING', 'amount' => '395.0', 'size' => '1.5 GB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '593', 'network' => 'AIRTEL', 'plan_type' => 'SME', 'amount' => '395.0', 'size' => '1.5 GB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '594', 'network' => 'AIRTEL', 'plan_type' => 'GIFTING', 'amount' => '1450.0', 'size' => '5.0 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '595', 'network' => 'AIRTEL', 'plan_type' => 'SME', 'amount' => '1460.0', 'size' => '5.0 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '596', 'network' => 'AIRTEL', 'plan_type' => 'GIFTING', 'amount' => '570.0', 'size' => '2.0 GB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '597', 'network' => 'AIRTEL', 'plan_type' => 'SME', 'amount' => '570.0', 'size' => '2.0 GB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '598', 'network' => 'AIRTEL', 'plan_type' => 'GIFTING', 'amount' => '490.0', 'size' => '3.2 GB', 'validity' => '3DAY VALIDITY'],
            ['data_id' => '599', 'network' => 'AIRTEL', 'plan_type' => 'SME', 'amount' => '490.0', 'size' => '3.2 GB', 'validity' => '3DAY VALIDITY'],
            ['data_id' => '600', 'network' => 'AIRTEL', 'plan_type' => 'GIFTING', 'amount' => '980.0', 'size' => '6.5 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '601', 'network' => 'AIRTEL', 'plan_type' => 'SME', 'amount' => '980.0', 'size' => '6.5 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '602', 'network' => 'AIRTEL', 'plan_type' => 'GIFTING', 'amount' => '1950.0', 'size' => '8.0 GB', 'validity' => '30DAYS VALIDITY'],
            ['data_id' => '603', 'network' => 'AIRTEL', 'plan_type' => 'SME', 'amount' => '1950.0', 'size' => '8.0 GB', 'validity' => '30DAYS VALIDITY'],
            ['data_id' => '604', 'network' => 'AIRTEL', 'plan_type' => 'GIFTING', 'amount' => '97000.0', 'size' => '60.0 GB', 'validity' => '60days(2month)'],
            ['data_id' => '605', 'network' => 'AIRTEL', 'plan_type' => 'SME', 'amount' => '97000.0', 'size' => '60.0 GB', 'validity' => '60days(2month)'],
            ['data_id' => '285', 'network' => 'GLO', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '395.0', 'size' => '1.0 GB', 'validity' => '30 days (C.G)'],
            ['data_id' => '286', 'network' => 'GLO', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '790.0', 'size' => '2.0 GB', 'validity' => '30 days (C.G)'],
            ['data_id' => '287', 'network' => 'GLO', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '1185.0', 'size' => '3.0 GB', 'validity' => '30 days (C.G)'],
            ['data_id' => '288', 'network' => 'GLO', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '1975.0', 'size' => '5.0 GB', 'validity' => '30 days (C.G)'],
            ['data_id' => '289', 'network' => 'GLO', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '3950.0', 'size' => '10.0 GB', 'validity' => '30 days (C.G)'],
            ['data_id' => '290', 'network' => 'GLO', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '198.0', 'size' => '500.0 MB', 'validity' => '30 days (C.G)'],
            ['data_id' => '291', 'network' => 'GLO', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '80.0', 'size' => '200.0 MB', 'validity' => '30 days (C.G)'],
            ['data_id' => '351', 'network' => 'GLO', 'plan_type' => 'GIFTING', 'amount' => '295.0', 'size' => '1.5 GB', 'validity' => 'AWOOF 1DAYS VALIDITY'],
            ['data_id' => '352', 'network' => 'GLO', 'plan_type' => 'GIFTING', 'amount' => '485.0', 'size' => '2.5 GB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '354', 'network' => 'GLO', 'plan_type' => 'GIFTING', 'amount' => '1950.0', 'size' => '10.0 GB', 'validity' => 'AWOOF 7DAYS VALIDITY'],
            ['data_id' => '369', 'network' => 'GLO', 'plan_type' => 'SME', 'amount' => '295.0', 'size' => '1.5 GB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '370', 'network' => 'GLO', 'plan_type' => 'SME', 'amount' => '485.0', 'size' => '2.5 GB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '371', 'network' => 'GLO', 'plan_type' => 'SME', 'amount' => '1950.0', 'size' => '10.0 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '546', 'network' => 'GLO', 'plan_type' => 'GIFTING', 'amount' => '1000.0', 'size' => '3.5 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '547', 'network' => 'GLO', 'plan_type' => 'SME', 'amount' => '1000.0', 'size' => '3.5 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '548', 'network' => 'GLO', 'plan_type' => 'GIFTING', 'amount' => '2000.0', 'size' => '8.5 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '549', 'network' => 'GLO', 'plan_type' => 'SME', 'amount' => '2000.0', 'size' => '8.5 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '550', 'network' => 'GLO', 'plan_type' => 'GIFTING', 'amount' => '4850.0', 'size' => '20.5 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '551', 'network' => 'GLO', 'plan_type' => 'SME', 'amount' => '4850.0', 'size' => '20.5 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '563', 'network' => 'GLO', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '280.0', 'size' => '1.0 GB', 'validity' => '7days'],
            ['data_id' => '564', 'network' => 'GLO', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '245.0', 'size' => '1.0 GB', 'validity' => '3days'],
            ['data_id' => '620', 'network' => 'GLO', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '850.0', 'size' => '3.0 GB', 'validity' => '7days validity'],
            ['data_id' => '621', 'network' => 'GLO', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '720.0', 'size' => '3.0 GB', 'validity' => '3days validity'],
            ['data_id' => '625', 'network' => 'GLO', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '1200.0', 'size' => '5.0 GB', 'validity' => '3DAYS VALIDITY'],
            ['data_id' => '626', 'network' => 'GLO', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '1460.0', 'size' => '5.0 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '7', 'network' => 'MTN', 'plan_type' => 'SME', 'amount' => '780.0', 'size' => '1.0 GB', 'validity' => '7days'],
            ['data_id' => '8', 'network' => 'MTN', 'plan_type' => 'SME', 'amount' => '1450.0', 'size' => '2.0 GB', 'validity' => '30 days'],
            ['data_id' => '44', 'network' => 'MTN', 'plan_type' => 'SME', 'amount' => '2450.0', 'size' => '3.5 GB', 'validity' => '30 days'],
            ['data_id' => '219', 'network' => 'MTN', 'plan_type' => 'SME', 'amount' => '485.0', 'size' => '500.0 MB', 'validity' => '7 days'],
            ['data_id' => '308', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '3450.0', 'size' => '7.0 GB', 'validity' => '1month(SME)2'],
            ['data_id' => '310', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '2450.0', 'size' => '3.5 GB', 'validity' => '1month(SME)2'],
            ['data_id' => '314', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '1450.0', 'size' => '2.0 GB', 'validity' => '1month(SME)2'],
            ['data_id' => '315', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '4400.0', 'size' => '10.0 GB', 'validity' => '1month(SME)2'],
            ['data_id' => '319', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '780.0', 'size' => '1.0 GB', 'validity' => 'Weekly +5MIN (SME)2'],
            ['data_id' => '330', 'network' => 'MTN', 'plan_type' => 'DATA SHARE', 'amount' => '1800.0', 'size' => '5.0 GB', 'validity' => '3weeks VALIDITY'],
            ['data_id' => '343', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '970.0', 'size' => '3.2 GB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '378', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '970.0', 'size' => '3.2 GB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '379', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '3450.0', 'size' => '11.0 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '403', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '485.0', 'size' => '1.0 GB', 'validity' => '1DAY VALIDITY+5min'],
            ['data_id' => '404', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '2450.0', 'size' => '6.0 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '405', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '17500.0', 'size' => '75.0 GB', 'validity' => '30days'],
            ['data_id' => '406', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '49500.0', 'size' => '200.0 GB', 'validity' => '60days'],
            ['data_id' => '407', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '4450.0', 'size' => '10.0 GB', 'validity' => '+15min Monthly'],
            ['data_id' => '408', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '80.0', 'size' => '75.0 MB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '409', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '750.0', 'size' => '2.5 GB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '410', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '750.0', 'size' => '2.0 GB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '412', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '590.0', 'size' => '1.5 GB', 'validity' => '2DAY VALIDITY'],
            ['data_id' => '413', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '5000.0', 'size' => '11.0 GB', 'validity' => '25min + 30days'],
            ['data_id' => '414', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '6480.0', 'size' => '16.5 GB', 'validity' => '30DAYS VALIDITY +25MIN'],
            ['data_id' => '416', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '7300.0', 'size' => '20.0 GB', 'validity' => '30DAYS VALIDITY'],
            ['data_id' => '417', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '8950.0', 'size' => '25.0 GB', 'validity' => '30days'],
            ['data_id' => '419', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '2910.0', 'size' => '4.2 GB', 'validity' => '+5mins monthly'],
            ['data_id' => '420', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '4450.0', 'size' => '10.0 GB', 'validity' => '30DAYS VALIDITY +15MIN'],
            ['data_id' => '429', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '485.0', 'size' => '1.0 GB', 'validity' => '1DAY VALIDITY+5min'],
            ['data_id' => '430', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '590.0', 'size' => '1.5 GB', 'validity' => '2DAY VALIDITY'],
            ['data_id' => '431', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '750.0', 'size' => '2.0 GB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '432', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '900.0', 'size' => '2.5 GB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '433', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '750.0', 'size' => '2.5 GB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '434', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '2450.0', 'size' => '6.0 GB', 'validity' => '7days validity'],
            ['data_id' => '438', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '2950.0', 'size' => '4.2 GB', 'validity' => '+5mins monthly'],
            ['data_id' => '440', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '3450.0', 'size' => '11.0 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '441', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '785.0', 'size' => '1.0 GB', 'validity' => '7DAYS VALIDITY +25MIN'],
            ['data_id' => '442', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '785.0', 'size' => '1.0 GB', 'validity' => '7DAYS VALIDITY +25MIN'],
            ['data_id' => '443', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '96.0', 'size' => '110.0 MB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '444', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '96.0', 'size' => '110.0 MB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '445', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '195.0', 'size' => '230.0 MB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '446', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '195.0', 'size' => '230.0 MB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '451', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '1450.0', 'size' => '2.0 GB', 'validity' => '30DAYS VALIDITY'],
            ['data_id' => '452', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '1450.0', 'size' => '2.0 GB', 'validity' => '30DAYS VALIDITY'],
            ['data_id' => '453', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '2450.0', 'size' => '3.5 GB', 'validity' => '30DAYS VALIDITY'],
            ['data_id' => '454', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '2450.0', 'size' => '3.5 GB', 'validity' => '30DAYS VALIDITY'],
            ['data_id' => '455', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '6480.0', 'size' => '16.5 GB', 'validity' => '30DAYS VALIDITY +10MIN'],
            ['data_id' => '456', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '3450.0', 'size' => '7.0 GB', 'validity' => '30DAYS VALIDITY +2gbnight'],
            ['data_id' => '457', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '3450.0', 'size' => '7.0 GB', 'validity' => '30DAYS VALIDITY +2gbnight'],
            ['data_id' => '458', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '7300.0', 'size' => '20.0 GB', 'validity' => '30DAYS VALIDITY'],
            ['data_id' => '459', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '8950.0', 'size' => '25.0 GB', 'validity' => '30DAYS VALIDITY'],
            ['data_id' => '462', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '80.0', 'size' => '75.0 MB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '463', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '5350.0', 'size' => '12.5 GB', 'validity' => '1Month'],
            ['data_id' => '464', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '6300.0', 'size' => '16.5 GB', 'validity' => '1month'],
            ['data_id' => '465', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '1480.0', 'size' => '3.5 GB', 'validity' => 'Weekly(SME)2'],
            ['data_id' => '466', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '2910.0', 'size' => '4.2 GB', 'validity' => '1month(SME)2'],
            ['data_id' => '467', 'network' => 'MTN', 'plan_type' => 'SME', 'amount' => '965.0', 'size' => '1.5 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '473', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '10800.0', 'size' => '36.0 GB', 'validity' => '30days'],
            ['data_id' => '474', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '15500.0', 'size' => '65.0 GB', 'validity' => '30 days'],
            ['data_id' => '475', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '17450.0', 'size' => '75.0 GB', 'validity' => '30 days'],
            ['data_id' => '476', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '35880.0', 'size' => '165.0 GB', 'validity' => '30 days'],
            ['data_id' => '479', 'network' => 'MTN', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '900.0', 'size' => '2.0 GB', 'validity' => '21 days to 30days'],
            ['data_id' => '480', 'network' => 'MTN', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '1350.0', 'size' => '3.0 GB', 'validity' => '21 to 30days validity'],
            ['data_id' => '481', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '900.0', 'size' => '2000.0 MB', 'validity' => '2GB 14 T0 21MONTHLY VALIDITY'],
            ['data_id' => '482', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '1350.0', 'size' => '3000.0 MB', 'validity' => '(3GB) 21 to 30days'],
            ['data_id' => '497', 'network' => 'MTN', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '340.0', 'size' => '500.0 MB', 'validity' => '(500MB) 7 days (C.G)'],
            ['data_id' => '498', 'network' => 'MTN', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '500.0', 'size' => '1.0 GB', 'validity' => '21dys to Monthly (C.G)'],
            ['data_id' => '500', 'network' => 'MTN', 'plan_type' => 'SME', 'amount' => '340.0', 'size' => '0.5 GB', 'validity' => '(500MB) 7DAYS VALIDITY'],
            ['data_id' => '501', 'network' => 'MTN', 'plan_type' => 'SME', 'amount' => '500.0', 'size' => '1000.0 MB', 'validity' => '=(1GB)21 to 30days VALIDITY'],
            ['data_id' => '502', 'network' => 'MTN', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '1800.0', 'size' => '5.0 GB', 'validity' => '3 weeks VALIDITY'],
            ['data_id' => '503', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '1800.0', 'size' => '5000.0 MB', 'validity' => '3weeks VALIDITY'],
            ['data_id' => '504', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '53500.0', 'size' => '250.0 GB', 'validity' => '30 days'],
            ['data_id' => '505', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '53500.0', 'size' => '250.0 GB', 'validity' => '30 days'],
            ['data_id' => '506', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '24500.0', 'size' => '90.0 GB', 'validity' => '60days(2month)'],
            ['data_id' => '507', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '24500.0', 'size' => '90.0 GB', 'validity' => '60days(2month)'],
            ['data_id' => '509', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '740.0', 'size' => '2.5 GB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '510', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '740.0', 'size' => '2.5 GB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '511', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '740.0', 'size' => '2.5 GB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '512', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '4900.0', 'size' => '20.0 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '513', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '4900.0', 'size' => '20.0 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '514', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '4900.0', 'size' => '20.0 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '538', 'network' => 'MTN', 'plan_type' => 'SME', 'amount' => '1800.0', 'size' => '5000.0 MB', 'validity' => '(5GB) 3 weeks VALIDITY'],
            ['data_id' => '539', 'network' => 'MTN', 'plan_type' => 'SME', 'amount' => '7300.0', 'size' => '20.0 GB', 'validity' => '30 days'],
            ['data_id' => '562', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '500.0', 'size' => '1000.0 MB', 'validity' => '21to 30days VALIDITY(1GB)'],
            ['data_id' => '566', 'network' => 'MTN', 'plan_type' => 'DATA SHARE', 'amount' => '340.0', 'size' => '500.0 MB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '567', 'network' => 'MTN', 'plan_type' => 'DATA SHARE', 'amount' => '500.0', 'size' => '1000.0 MB', 'validity' => '=(1gb)21to monthly VALIDITY'],
            ['data_id' => '568', 'network' => 'MTN', 'plan_type' => 'DATA SHARE', 'amount' => '900.0', 'size' => '2.0 GB', 'validity' => '21 to 30 DAYS VALIDITY'],
            ['data_id' => '569', 'network' => 'MTN', 'plan_type' => 'DATA SHARE', 'amount' => '1350.0', 'size' => '3.0 GB', 'validity' => '21 to 30DAYS VALIDITY'],
            ['data_id' => '570', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '1800.0', 'size' => '5.0 GB', 'validity' => '3weeks VALIDITY'],
            ['data_id' => '571', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '1350.0', 'size' => '3.0 GB', 'validity' => '21 to 30DAYS VALIDITY'],
            ['data_id' => '572', 'network' => 'MTN', 'plan_type' => 'SME', 'amount' => '1350.0', 'size' => '3000.0 MB', 'validity' => '(3GB) 21 to 30days'],
            ['data_id' => '573', 'network' => 'MTN', 'plan_type' => 'SME', 'amount' => '900.0', 'size' => '2000.0 MB', 'validity' => '=(2GB) 21 to 30days VALIDITY'],
            ['data_id' => '574', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '500.0', 'size' => '1000.0 MB', 'validity' => '(1GB)21to 30 days VALIDITY'],
            ['data_id' => '575', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '500.0', 'size' => '1000.0 MB', 'validity' => '(1GB)21dys to monthly VALIDITY'],
            ['data_id' => '576', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '123000.0', 'size' => '800.0 GB', 'validity' => '365 DAYS VALIDITY'],
            ['data_id' => '577', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '123000.0', 'size' => '800.0 GB', 'validity' => '365 DAYS VALIDITY'],
            ['data_id' => '578', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '123000.0', 'size' => '800.0 GB', 'validity' => '365 DAYS VALIDITY'],
            ['data_id' => '579', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '1800.0', 'size' => '5.0 GB', 'validity' => '3 weeks VALIDITY'],
            ['data_id' => '580', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '900.0', 'size' => '2000.0 MB', 'validity' => '=(2GB) 21 to 30days VALIDITY'],
            ['data_id' => '581', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '900.0', 'size' => '2000.0 MB', 'validity' => '14 TO 21DAYS VALIDITY'],
            ['data_id' => '582', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '1350.0', 'size' => '3.0 GB', 'validity' => '21days to 30days VALIDITY'],
            ['data_id' => '583', 'network' => 'MTN', 'plan_type' => 'SME', 'amount' => '440.0', 'size' => '1000.0 MB', 'validity' => '7DAYS VALIDITY (1GB)'],
            ['data_id' => '584', 'network' => 'MTN', 'plan_type' => 'CORPORATE GIFTING', 'amount' => '440.0', 'size' => '1.0 GB', 'validity' => '=(1GB) 7DAYS VALIDITY'],
            ['data_id' => '585', 'network' => 'MTN', 'plan_type' => 'DATA SHARE', 'amount' => '440.0', 'size' => '1.0 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '586', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '440.0', 'size' => '1000.0 MB', 'validity' => '=(1GB) 7DAYS VALIDITY'],
            ['data_id' => '587', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '440.0', 'size' => '1000.0 MB', 'validity' => '=(1GB) 7DAYS VALIDITY'],
            ['data_id' => '588', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '440.0', 'size' => '1000.0 MB', 'validity' => '=(1GB)7DAYS VALIDITY'],
            ['data_id' => '589', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '340.0', 'size' => '0.5 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '590', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '340.0', 'size' => '0.5 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '591', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '340.0', 'size' => '0.5 GB', 'validity' => '7DAYS VALIDITY'],
            ['data_id' => '606', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '291.0', 'size' => '1.0 GB', 'validity' => '3DAYS{FOR INSTA/TIKTOK/YOUTUBE'],
            ['data_id' => '607', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '291.0', 'size' => '1.0 GB', 'validity' => '3DAYS{FOR INSTA/TIKTOK/YOUTUBE'],
            ['data_id' => '608', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '390.0', 'size' => '2.0 GB', 'validity' => '7DAYS FOR TIKTOK ONLY'],
            ['data_id' => '609', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '390.0', 'size' => '2.0 GB', 'validity' => '7DAYS FOR TIKTOK ONLY'],
            ['data_id' => '610', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '120.0', 'size' => '200.0 MB', 'validity' => '1DAY/24HRS SOCIAL ONLY'],
            ['data_id' => '611', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '120.0', 'size' => '200.0 MB', 'validity' => '1DAY/24HRS SOCIAL ONLY'],
            ['data_id' => '614', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '250.0', 'size' => '1.0 GB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '615', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '250.0', 'size' => '1.0 GB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '616', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '210.0', 'size' => '1.0 GB', 'validity' => '1DAY VALIDITY(no sms delivery)'],
            ['data_id' => '617', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '520.0', 'size' => '2.5 GB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '618', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '520.0', 'size' => '2.5 GB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '619', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '520.0', 'size' => '2.5 GB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '622', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '441.0', 'size' => '750.0 MB', 'validity' => '3day +Free 1hr YT/IG/Tik'],
            ['data_id' => '623', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '441.0', 'size' => '750.0 MB', 'validity' => '3day +Free 1hr YT/IG/Tik'],
            ['data_id' => '624', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '441.0', 'size' => '750.0 MB', 'validity' => '3day +Free 1hrYT\\IG/TikT'],
            ['data_id' => '627', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '970.0', 'size' => '3.5 GB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '628', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '970.0', 'size' => '3.5 GB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '629', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '970.0', 'size' => '3.5 GB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '630', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '1164.0', 'size' => '4.0 GB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '631', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '1164.0', 'size' => '4.0 GB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '632', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '1164.0', 'size' => '4.0 GB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '633', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '1480.0', 'size' => '5.5 GB', 'validity' => '2DAYS VALIDITY'],
            ['data_id' => '634', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '9800.0', 'size' => '34.0 GB', 'validity' => '30DAYS VALIDITY'],
            ['data_id' => '635', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '9800.0', 'size' => '34.0 GB', 'validity' => '30DAYS VALIDITY'],
            ['data_id' => '636', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '9800.0', 'size' => '34.0 GB', 'validity' => '30DAYS VALIDITY'],
            ['data_id' => '637', 'network' => 'MTN', 'plan_type' => 'SME2', 'amount' => '250.0', 'size' => '1.0 GB', 'validity' => '1DAY'],
            ['data_id' => '638', 'network' => 'MTN', 'plan_type' => 'GIFTING', 'amount' => '210.0', 'size' => '1.0 GB', 'validity' => '1DAY VALIDITY'],
            ['data_id' => '639', 'network' => 'MTN', 'plan_type' => 'DATA COUPONS', 'amount' => '210.0', 'size' => '1.0 GB', 'validity' => '1DAY VALIDITY'],
        ];

        foreach ($data as $item) {
            $item['created_at'] = now();
            $item['updated_at'] = now();
            \Illuminate\Support\Facades\DB::table('sme_datas')->insert($item);
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('sme_datas');
    }
};
